### ISSUE TITLE
pages to review for august release

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/update-content-registry#59]
Here are links with markdown content from the sprint for preview/testing purposes.

## Production

Anatomy
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:anatomy/id=UBERON%3A0000007 Embl link, Knowledge Graph text, GTEx widget

Compound
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=G99997WS Glycan only
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=1000 PubChem and DrugCentral
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=10000009 PubChem and Glycan
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=10000456 PubChem and Knowledge Graph

Disease
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:disease/id=DOID%3A9970 links and associated genes/proteins
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:disease/id=DOID%3A10016 links and associated genes/proteins

Gene
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000000003 Aliases, LINCS text, and GTEx, LINCS, transcript , and UCSD iframe
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000000419 Aliases, LINCS text and MetGene, GTEx, LINCS and transcript iframes
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000001626 Aliases, LINCS text, Diseases, and MetGene, GTEx, LINCS and transcript iframes
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000133136 LINCS text and iframe

Protein
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=A0A023IKK2 alias links and diseases
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=P0DTC2 alias links only
- [ ] https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=P14210 alias links only

## Staging

Anatomy
- [ ] UBERON:0000007 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:anatomy/nid=1 Embl link, Knowledge Graph text, GTEx widget
- [ ] UBERON:0000948 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:anatomy/nid=114 Embl link and Knowledge Graph text
- [ ] UBERON:0000002 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:anatomy/nid=53 Embl link only

Gene

- [ ] ENSG00000001626  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:gene/nid=39 Aliases, LINCS text, Diseases, and MetGene, GTEx, LINCS and transcript iframes
- [ ] ENSG00000000419  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:gene/nid=35 Aliases, LINCS text and MetGene, GTEx, LINCS and transcript iframes
- [ ] ENSG00000133136  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:gene/nid=10523 LINCS text and iframe
- [ ] ENSG00000000003 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:gene/nid=3892 Aliases, LINCS text, and GTEx, LINCS, transcript , and UCSD iframe

Disease
- [ ] DOID:9970 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:disease/nid=8 links only
- [ ] DOID:10016 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:disease/nid=108 links plus associated genes and proteins

Compound
- [ ] 1000 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:compound/nid=33764 PubChem and DrugCentral
- [ ] 10000009  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:compound/nid=1 PubChem and Glycan
- [ ] G99997WS  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:compound/nid=33754 Glycan only
- [ ] 10000456  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:compound/nid=33765 PubChem and Knowledge Graph

Protein
- [ ] P14210 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:protein/nid=24102 alias links only
- [ ] P0DTC2 https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:protein/nid=23502 alias links only
- [ ] A0A023IKK2  https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:protein/nid=1 alias links and diseases

**Comment by raynamharris** [comment]
![Screen Shot 2022-08-19 at 12 55 53 PM](https://user-images.githubusercontent.com/7544197/185697424-63a9dfe4-92ed-4353-b887-677f92600833.png)
![Screen Shot 2022-08-19 at 12 55 59 PM](https://user-images.githubusercontent.com/7544197/185697433-78fb8ceb-8215-4f55-868d-6a1f2cd4bd66.png)
![Screen Shot 2022-08-19 at 12 56 05 PM](https://user-images.githubusercontent.com/7544197/185697440-799cf193-6992-4c85-b9c0-09cf17fc05c4.png)
![Screen Shot 2022-08-19 at 12 56 11 PM](https://user-images.githubusercontent.com/7544197/185697443-e58abdda-0972-43c8-8167-c9683b7fd7c7.png)
![Screen Shot 2022-08-19 at 12 56 18 PM](https://user-images.githubusercontent.com/7544197/185697446-368828f0-84b9-4fd3-a69d-acb11fdcf7bb.png)

**Comment by raynamharris** [comment]
created some short tests lists with the IDs above and pushed some content to production for review. See branch `test-prod` at https://github.com/nih-cfde/update-content-registry/tree/prod-test/data/inputs/test

**Comment by raynamharris** [comment]
you can run this R code to open up all the pages for review in a browser

```r
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:anatomy/id=UBERON%3A0000007")
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=G99997WS")
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=1000")
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=10000009")        
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:compound/id=10000456") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:disease/id=DOID%3A9970") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:disease/id=DOID%3A10016") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000000003") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000000419") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=ENSG00000001626") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/id=NSG00000133136") 
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=A0A023IKK2")
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=P0DTC2")
browseURL("https://app.nih-cfde.org/chaise/record/#1/CFDE:protein/id=P14210")
```

**Comment by raynamharris** [comment]
done.
