### ISSUE TITLE
october updates

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/update-content-registry#73]
working on a solution that replaces the gigantic #68 with a few smaller prs that do specific things so it will be easier to review.

- [ ] generating statistics for testing and reporting #74
- [ ] retrieve a list of all CV_IDs in the production portal  #75 
- [ ] update scripts to filter compound IDs #76 
- [ ] update scripts to filter gene IDs #77
- [ ] update scripts to filter disease IDs
- [ ] update scripts to filter protein IDs
- [ ] update scripts to filter anatomy IDs
